
meta_product_name: "Subscriptio"
meta_title: "Subscriptio - Stop losing money: act now"
meta_description: "Subscriptio helps you to stop overpaying for your software subscriptions"
meta_image: "subscriptio-logo.png" # should exist in `app/assets/images/`
